// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pak_Railway_Reservation_System;

#nullable disable

namespace PakRailwayReservationSystem.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.CancelTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<float>("Bil")
                        .HasColumnType("real");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CancelationFine")
                        .HasColumnType("real");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoachNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfTravel")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PNRNo")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPassenger")
                        .HasColumnType("int");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CancelTickets");
                });

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.PassengerDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<float>("Bil")
                        .HasColumnType("real");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoachNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfTravel")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PNRNo")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPassenger")
                        .HasColumnType("int");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PassengerDetails");
                });

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.Register", b =>
                {
                    b.Property<int>("RegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisterId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("UserConfirmPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegisterId");

                    b.ToTable("Registers");

                    b.HasData(
                        new
                        {
                            RegisterId = 1,
                            Age = 19,
                            CNIC = "4230169743053",
                            Gender = "Male",
                            PhoneNo = "03061872272",
                            UserConfirmPassword = "$2a$10$AJc4UTwgw5CPgnthQUv0qulb84r/FE4dQ5bluq81JrcEys0.BBByO",
                            UserEmail = "samad@gmail.com",
                            UserImage = "Default_User_Image.png",
                            UserName = "Abdulsamad",
                            UserPassword = "$2a$10$AJc4UTwgw5CPgnthQUv0qulb84r/FE4dQ5bluq81JrcEys0.BBByO",
                            UserRole = "Admin"
                        });
                });

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("RailwayDivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            RailwayDivisionName = "Sindh",
                            StationCode = "KHI",
                            StationImage = "Karachi_cantt._station_full_facade.jpg",
                            StationName = "Karachi"
                        },
                        new
                        {
                            StationId = 2,
                            RailwayDivisionName = "Sindh",
                            StationCode = "HYD",
                            StationImage = "Hyderabad_Junction_railway_station_(inside_view).jpg",
                            StationName = "Hyderabad"
                        },
                        new
                        {
                            StationId = 3,
                            RailwayDivisionName = "Sindh",
                            StationCode = "RHR",
                            StationImage = "rohri_image.jpg",
                            StationName = "Rohri"
                        },
                        new
                        {
                            StationId = 4,
                            RailwayDivisionName = "Punjab",
                            StationCode = "LHE",
                            StationImage = "Lahore_Railway_Station_09.jpg",
                            StationName = "Lahore"
                        },
                        new
                        {
                            StationId = 5,
                            RailwayDivisionName = "Punjab",
                            StationCode = "ISB",
                            StationImage = "Islamabad_Railway_Station_8.png",
                            StationName = "Islamabad"
                        });
                });

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.TrainDetail", b =>
                {
                    b.Property<int>("TrainDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainDetailId"));

                    b.Property<int>("ACBusiness")
                        .HasColumnType("int");

                    b.Property<int>("ACLower")
                        .HasColumnType("int");

                    b.Property<int>("Compartments")
                        .HasColumnType("int");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ecomomy")
                        .HasColumnType("int");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainDetailId");

                    b.ToTable("TrainDetails");

                    b.HasData(
                        new
                        {
                            TrainDetailId = 1,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 30,
                            From = "Karachi",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainDetailId = 2,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 30,
                            From = "Lahore",
                            To = "Karachi",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainDetailId = 3,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 17, 3, 0, 0, DateTimeKind.Local),
                            Ecomomy = 30,
                            From = "Haderabad",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainDetailId = 4,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 30,
                            From = "Lahore",
                            To = "Haderabad",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainDetailId = 5,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 22, 3, 0, 0, DateTimeKind.Local),
                            Ecomomy = 30,
                            From = "Rohri",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainDetailId = 6,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 30,
                            From = "Lahore",
                            To = "Rohri",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainDetailId = 7,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Karachi",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 8,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 30, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Islamabad",
                            To = "Karachi",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 9,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 17, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Hyderabad",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 10,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Islamabad",
                            To = "Hyderabad",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 11,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 21, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Rohri",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 12,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Islamabad",
                            To = "Rohri",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 13,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 18, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Lahore",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 14,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 25,
                            From = "Islamabad",
                            To = "Lahore",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainDetailId = 15,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 14, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 35,
                            From = "Karachi",
                            To = "Hyderabad",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainDetailId = 16,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 30, 0, 0, DateTimeKind.Local),
                            Ecomomy = 35,
                            From = "Hyderabad",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainDetailId = 17,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 16, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 35,
                            From = "Hyderabad",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainDetailId = 18,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 18, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 35,
                            From = "Rohri",
                            To = "Hyderabad",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainDetailId = 19,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 15, 30, 0, 0, DateTimeKind.Local),
                            Ecomomy = 35,
                            From = "Karachi",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainDetailId = 20,
                            ACBusiness = 30,
                            ACLower = 30,
                            Compartments = 3,
                            Departure = new DateTime(2024, 1, 15, 17, 0, 0, 0, DateTimeKind.Local),
                            Ecomomy = 35,
                            From = "Rohri",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        });
                });

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.TrainFare", b =>
                {
                    b.Property<int>("TrainFareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainFareId"));

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<float>("Fare")
                        .HasColumnType("real");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainFareId");

                    b.ToTable("TrainFares");

                    b.HasData(
                        new
                        {
                            TrainFareId = 1,
                            Class = "AC Lower/Standard",
                            Distance = 1200f,
                            Fare = 7000f,
                            From = "Karachi",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 2,
                            Class = "AC Business",
                            Distance = 1200f,
                            Fare = 9000f,
                            From = "Karachi",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 3,
                            Class = "Economy",
                            Distance = 1200f,
                            Fare = 4000f,
                            From = "Karachi",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 4,
                            Class = "AC Lower/Standard",
                            Distance = 1036f,
                            Fare = 6000f,
                            From = "Hyderabad",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 5,
                            Class = "AC Business",
                            Distance = 1036f,
                            Fare = 8000f,
                            From = "Hyderabad",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 6,
                            Class = "Economy",
                            Distance = 1036f,
                            Fare = 3000f,
                            From = "Hyderabad",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 7,
                            Class = "AC Lower/Standard",
                            Distance = 800f,
                            Fare = 5000f,
                            From = "Rohri",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 8,
                            Class = "AC Business",
                            Distance = 800f,
                            Fare = 6000f,
                            From = "Rohri",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 9,
                            Class = "Economy",
                            Distance = 800f,
                            Fare = 2000f,
                            From = "Rohri",
                            To = "Lahore",
                            TrainName = "1UP Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 10,
                            Class = "AC Lower/Standard",
                            Distance = 1450f,
                            Fare = 8000f,
                            From = "Karachi",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 11,
                            Class = "AC Business",
                            Distance = 1450f,
                            Fare = 10000f,
                            From = "Karachi",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 12,
                            Class = "Economy",
                            Distance = 1450f,
                            Fare = 4500f,
                            From = "Karachi",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 13,
                            Class = "AC Lower/Standard",
                            Distance = 1280f,
                            Fare = 7000f,
                            From = "Hyderabad",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 14,
                            Class = "AC Business",
                            Distance = 1280f,
                            Fare = 9000f,
                            From = "Hyderabad",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 15,
                            Class = "Economy",
                            Distance = 1280f,
                            Fare = 4500f,
                            From = "Hyderabad",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 16,
                            Class = "AC Lower/Standard",
                            Distance = 1050f,
                            Fare = 8000f,
                            From = "Rohri",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 17,
                            Class = "AC Business",
                            Distance = 1050f,
                            Fare = 10000f,
                            From = "Rohri",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 18,
                            Class = "Economy",
                            Distance = 1050f,
                            Fare = 4500f,
                            From = "Rohri",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 19,
                            Class = "AC Lower/Standard",
                            Distance = 375f,
                            Fare = 5000f,
                            From = "Lahore",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 20,
                            Class = "AC Business",
                            Distance = 375f,
                            Fare = 7000f,
                            From = "Lahore",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 21,
                            Class = "Economy",
                            Distance = 375f,
                            Fare = 2000f,
                            From = "Lahore",
                            To = "Islamabad",
                            TrainName = "1UP Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 22,
                            Class = "AC Lower/Standard",
                            Distance = 165f,
                            Fare = 1500f,
                            From = "Karachi",
                            To = "Hyderabad",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 23,
                            Class = "AC Business",
                            Distance = 165f,
                            Fare = 3000f,
                            From = "Karachi",
                            To = "Hyderabad",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 24,
                            Class = "Economy",
                            Distance = 165f,
                            Fare = 1000f,
                            From = "Karachi",
                            To = "Hyderabad",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 25,
                            Class = "AC Lower/Stander",
                            Distance = 480f,
                            Fare = 3000f,
                            From = "Karachi",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 26,
                            Class = "AC Business",
                            Distance = 480f,
                            Fare = 5000f,
                            From = "Karachi",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 27,
                            Class = "Economy",
                            Distance = 480f,
                            Fare = 1500f,
                            From = "Karachi",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 28,
                            Class = "AC Lower/Standard",
                            Distance = 315f,
                            Fare = 2000f,
                            From = "Hyderabad",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 29,
                            Class = "AC Business",
                            Distance = 315f,
                            Fare = 4000f,
                            From = "Hyderabad",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 30,
                            Class = "Economy",
                            Distance = 315f,
                            Fare = 1000f,
                            From = "Hyderabad",
                            To = "Rohri",
                            TrainName = "1UP Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 31,
                            Class = "AC Lower/Standard",
                            Distance = 1200f,
                            Fare = 7000f,
                            From = "Lahore",
                            To = "Karachi",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 32,
                            Class = "AC Business",
                            Distance = 1200f,
                            Fare = 9000f,
                            From = "Lahore",
                            To = "Karachi",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 33,
                            Class = "Economy",
                            Distance = 1200f,
                            Fare = 4000f,
                            From = "Lahore",
                            To = "Karachi",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 34,
                            Class = "AC Lower/Standard",
                            Distance = 1036f,
                            Fare = 6000f,
                            From = "Lahore",
                            To = "Hyderabad",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 35,
                            Class = "AC Business",
                            Distance = 11036f,
                            Fare = 8000f,
                            From = "Lahore",
                            To = "Hyderabad",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 36,
                            Class = "Economy",
                            Distance = 1036f,
                            Fare = 3000f,
                            From = "Lahore",
                            To = "Hyderabad",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 37,
                            Class = "AC Lower/Standard",
                            Distance = 800f,
                            Fare = 5000f,
                            From = "Lahore",
                            To = "Rohri",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 38,
                            Class = "AC Business",
                            Distance = 800f,
                            Fare = 6000f,
                            From = "Lahore",
                            To = "Rohri",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 39,
                            Class = "Economy",
                            Distance = 800f,
                            Fare = 2000f,
                            From = "Lahore",
                            To = "Rohri",
                            TrainName = "2DN Karakoram Express"
                        },
                        new
                        {
                            TrainFareId = 40,
                            Class = "AC Lower/Standard",
                            Distance = 1450f,
                            Fare = 8000f,
                            From = "Islamabad",
                            To = "Karachi",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 41,
                            Class = "AC Business",
                            Distance = 1450f,
                            Fare = 10000f,
                            From = "Islamabad",
                            To = "Karachi",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 42,
                            Class = "Economy",
                            Distance = 1450f,
                            Fare = 4500f,
                            From = "Islamabad",
                            To = "Karachi",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 43,
                            Class = "AC Lower/Standard",
                            Distance = 1280f,
                            Fare = 7000f,
                            From = "Islamabad",
                            To = "Hyderabad",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 44,
                            Class = "AC Business",
                            Distance = 1280f,
                            Fare = 9000f,
                            From = "Islamabad",
                            To = "Hyderabad",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 45,
                            Class = "Economy",
                            Distance = 1280f,
                            Fare = 4500f,
                            From = "Islamabad",
                            To = "Hyderabad",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 46,
                            Class = "AC Lower/Standard",
                            Distance = 1050f,
                            Fare = 8000f,
                            From = "Islamabad",
                            To = "Rohri",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 47,
                            Class = "AC Business",
                            Distance = 1050f,
                            Fare = 10000f,
                            From = "Islamabad",
                            To = "Rohri",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 48,
                            Class = "Economy",
                            Distance = 1050f,
                            Fare = 4500f,
                            From = "Islamabad",
                            To = "Rohri",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 49,
                            Class = "AC Lower/Stander",
                            Distance = 375f,
                            Fare = 5000f,
                            From = "Islamabad",
                            To = "Lahore",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 50,
                            Class = "AC Business",
                            Distance = 375f,
                            Fare = 7000f,
                            From = "Islamabad",
                            To = "Lahore",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 51,
                            Class = "Economy",
                            Distance = 375f,
                            Fare = 2000f,
                            From = "Islamabad",
                            To = "Lahore",
                            TrainName = "2DN Green Line Express"
                        },
                        new
                        {
                            TrainFareId = 52,
                            Class = "AC Lower/Standard",
                            Distance = 165f,
                            Fare = 1500f,
                            From = "Hyderabad",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 53,
                            Class = "AC Business",
                            Distance = 165f,
                            Fare = 3000f,
                            From = "Hyderabad",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 54,
                            Class = "Economy",
                            Distance = 165f,
                            Fare = 1000f,
                            From = "Hyderabad",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 55,
                            Class = "AC Lower/Stander",
                            Distance = 480f,
                            Fare = 3000f,
                            From = "Rohri",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 56,
                            Class = "AC Business",
                            Distance = 480f,
                            Fare = 5000f,
                            From = "Rohri",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 57,
                            Class = "Economy",
                            Distance = 480f,
                            Fare = 1500f,
                            From = "Rohri",
                            To = "Karachi",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 58,
                            Class = "AC Lower/Standard",
                            Distance = 315f,
                            Fare = 2000f,
                            From = "Rohri",
                            To = "Hyderabad",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 59,
                            Class = "AC Business",
                            Distance = 315f,
                            Fare = 4000f,
                            From = "Rohri",
                            To = "Hyderabad",
                            TrainName = "2DN Tezgam Express"
                        },
                        new
                        {
                            TrainFareId = 60,
                            Class = "Economy",
                            Distance = 315f,
                            Fare = 1000f,
                            From = "Rohri",
                            To = "Hyderabad",
                            TrainName = "2DN Tezgam Express"
                        });
                });

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.TrainSchedule", b =>
                {
                    b.Property<int>("TrainScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainScheduleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainScheduleId");

                    b.ToTable("TrainSchedules");
                });

            modelBuilder.Entity("Pak_Railway_Reservation_System.Models.TrevellerInfo", b =>
                {
                    b.Property<int>("TrevellerInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrevellerInfoId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CNIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrevellerInfoId");

                    b.ToTable("TrevellerInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
